#pragma once
#include <vector>
#include <string>
#include <cstdint>
#include <cstdio>
#include <cerrno>
#include <cstdlib>
#include "hashmap.hpp"

using namespace std;

const size_t k_max_msg = 32<< 20; // 32MB
const size_t k_max_args = 200 * 1000;

struct Conn
{
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    vector<uint8_t> incoming; // data to be parsed by the application
    vector<uint8_t> outgoing; // responses generated by the application
};

struct Response{
    uint32_t status = 0;
    vector<uint8_t> payload;      // indicates the message content
};

struct Entry {
    string key ;
    string val;
    HashNode node; // intrusive ds -> meant to be embedded not referenced.
};

enum {
    RES_OK = 0,
    RES_ERR = 1,    // error
    RES_NX = 2,     // key not found
};

#define container_of(ptr, T, member) \
    ((T *)( (char *)ptr - offsetof(T, member) ))

void die(const char *msg)
{
    int err = errno;
    fprintf(stderr, "[%d] %s\n", err, msg);
    abort();
}
static void msg(const char *msg)
{
    fprintf(stderr, "%s\n", msg);
}
